---
# tasks file for nginx
- name: install nginx
  ansible.builtin.apt:
    name: nginx
    state: present
    update_cache: yes
- name: Create a folder in home directory
  ansible.builtin.file:
    path: /etc/some_directory
    state: directory
    mode: '0755'